### ISSUE TITLE
no proper error if training file path is wrong

### ISSUE THREAD

**Issue by ashishonce** [Azure/aml-run#20]
if user gives wrong "runconfig_python_file", or the path is wrong , the code throws below error

![image](https://user-images.githubusercontent.com/12728754/80720646-d52b0b80-8b1a-11ea-9745-1f8d06bc992a.png)

this error is not explicit why issue has come and looks like the code inherently threw an error.  while actually there was in exception during module import execution

**Comment by marvinbuss** [comment]
@ashishonce This will be adressed in the next release. I found the issue by using unit tests.
