### ISSUE TITLE
This action stops with an exception, when no metrics are collected with run context

### ISSUE THREAD

**Issue by totosan** [Azure/aml-run#33]
If you are not using any kind of metric logging, using the run context from azureml sdk, this action crashes, because of an empty metrics list.
![image](https://user-images.githubusercontent.com/7992807/82949030-32dc3780-9fa3-11ea-99e0-198380e49c3b.png)

Following is my training script:
- (should be *.py) [test_train.txt](https://github.com/Azure/aml-run/files/4684988/test_train.txt) 
- You can see that there is only the assignment of run context in line 20 
- no other use of run.log(...) or others
- adding `run.log(...)` only one time, the pipeline completes the step successfully

**Comment by totosan** [comment]
ok, I think, this is resolved with the bug fix here #32, because the faulty line was commented out. I'll retry my runs. And give feedback next day.

**Comment by totosan** [comment]
For sure, it is fixed in latest version (v1.2.2). The line 172 in main.py cannot be called anymore. 
But consider a `If not null or empty....` before calling `experiment = Exp[0]`, when `convert_to_markdown` is used somewhere else. Thx a lot. I'll keep this open, if you like to fix it anyway, so that you can assign this issue to the fixed line. Otherwise, please close this, if not of interest.

**Comment by marvinbuss** [comment]
@totosan Thanks for submitting this. Another user reported a similar issue yesterday, which is why we released a quick fix (v1.2.2). We will fix this in the next release and enable the output again. There is already a PR, which includes some additional tests. We just have to make some changes to the function.
