### ISSUE TITLE
The action uses a personal (?) docker base image

### ISSUE THREAD

**Issue by marcindulak** [Azure/aml-run#56]
https://github.com/Azure/aml-run/blob/682294ea9f50795b04b27c030f4ada40407116ec/Dockerfile#L1

The problem is also present in other aml-* github actions.

**Comment by marvinbuss** [comment]
We will work on further improvements in the upcoming months. For now this image comes from my GitHub Container Registry.

**Comment by marcindulak** [comment]
It would be nice if the issue stays open until it's fixed or declined.
