### ISSUE TITLE
code/main.py: TypeError: get_metrics() got an unexpected keyword argument 'recursive'

### ISSUE THREAD

**Issue by marcindulak** [Azure/aml-run#57]
I'm using https://github.com/Azure/aml-run/commit/e1efa559107a525e0ef78dd3beb38464b60cf749 with azureml-sdk 1.21.0 and HyperDriveConfig, and getting

```
Traceback (most recent call last):
  File "/code/main.py", line 238, in <module>
    main()
  File "/code/main.py", line 189, in main
    run_metrics = run.get_metrics(recursive=True)
TypeError: get_metrics() got an unexpected keyword argument 'recursive'
```

Remove `recursive=True` https://github.com/marcindulak/aml-run/pull/1 as a workaround allows the run to finish.

**Comment by marvinbuss** [comment]
Hi @marcindulak,
Which version of the run action are you using? `v1` or a specific version?

**Comment by marvinbuss** [comment]
@marcindulak  Can you please test the new version of the run action by replacing `v1` with `azureml_1_21`?
Let me know whether that solves your issue.

**Comment by marcindulak** [comment]
https://github.com/Azure/aml-run/commit/9368ee2f99915df878e18ab424fb5ee648415c11 (azureml_1_21) does not solve the issue.

**Comment by marvinbuss** [comment]
Hi @marcindulak,
I just looked at this in the morning and reproduced the issue. I am now returning the right metrics based on the type of the run.
`azureml_1_21` should now work. Can you please give it another try?
Sorry for the issues you are experiencing and many thanks for collaborating. 👍

**Comment by marcindulak** [comment]
Yes, https://github.com/Azure/aml-run/commit/d83832bd219fccb2a38f2653ca53ae8504e26d66 `azureml_1_21` solves the problem for me.

**Comment by marvinbuss** [comment]
Great. Thanks for confirming @marcindulak. I will create a new release later today or tomorrow morning and then you can go back to using the `v1` tag or the specific tag of the new version. Will give you an update here and close the issue once the PR is merged.

**Comment by marvinbuss** [comment]
Hi @marcindulak,
Sorry that it took so long. I upgraded all Actions a couple of minutes ago and you should be able to switch back to `v1`. The bug should not exist anymore.
Would appreciate, if you could confirm.

**Comment by marcindulak** [comment]
https://github.com/Azure/aml-run/commit/58862473de9e6c49958fd3ee99152d696e41ee60 master works for me.
