### ISSUE TITLE
Convert to Markdown cannot handle dicts

### ISSUE THREAD

**Issue by marvinbuss** [Azure/aml-run#8]
![image](https://user-images.githubusercontent.com/34542414/78472653-f6c2ee00-773a-11ea-88cd-04aa5f16d718.png)

If someone submits a pipeline to Azure Machine Learning, the `convert_to_markdown` function can receive nested dicts. The function cannot handle this and fails. This needs to be fixed.

Sample dict that needs to be parsed:
{'HD_9cbf07dc-db35-4700-adc3-92253a378992': {'best_child_by_primary_metric': {'metric_name': ['mse',
    'mse',
    'mse'],
   'timestamp': ['2020-03-30 07:58:40.110108+00:00',
    '2020-03-30 07:59:42.417631+00:00',
    '2020-03-30 07:59:42.417631+00:00'],
   'run_id': ['HD_9cbf07dc-db35-4700-adc3-92253a378992_2',
    'HD_9cbf07dc-db35-4700-adc3-92253a378992_1',
    'HD_9cbf07dc-db35-4700-adc3-92253a378992_1'],
   'metric_value': [0.4896792910300023,
    0.33284572706891424,
    0.33284572706891424],
   'final': [False, False, True]}},
 'HD_9cbf07dc-db35-4700-adc3-92253a378992_0': {'AUC': 0.6562945178135493,
  'RMSE': 0.05120842417634075,
  'pAUC': 0.2812047761829226,
  'mse': 0.9367719704449606,
  'TimeSeries comparison': 'aml://artifactId/ExperimentRun/dcid.HD_9cbf07dc-db35-4700-adc3-92253a378992_0/TimeSeries comparison_1585555145.png'},
 'HD_9cbf07dc-db35-4700-adc3-92253a378992_1': {'AUC': 0.3573103979675637,
  'pAUC': 0.5616569664904285,
  'RMSE': 0.6161010679565609,
  'mse': 0.33284572706891424,
  'TimeSeries comparison': 'aml://artifactId/ExperimentRun/dcid.HD_9cbf07dc-db35-4700-adc3-92253a378992_1/TimeSeries comparison_1585555146.png'},
 'HD_9cbf07dc-db35-4700-adc3-92253a378992_2': {'AUC': 0.1200601984180878,
  'pAUC': 0.5805687333099157,
  'RMSE': 0.09691275977364577,
  'mse': 0.4896792910300023,
  'TimeSeries comparison': 'aml://artifactId/ExperimentRun/dcid.HD_9cbf07dc-db35-4700-adc3-92253a378992_2/TimeSeries comparison_1585555076.png'}}

**Comment by marvinbuss** [comment]
I commented out the code until we fix this, so that users do not run into this issue.

**Comment by awmatheson** [comment]
Is this acceptable as output:

## Experiment: HD_9cbf07dc-db35-4700-adc3-92253a378992 

| Run ID | Parameter | Value |
| ----- | ----- | ----- |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_0 | AUC | 0.656 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_0 | RMSE | 0.0512 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_0 | pAUC | 0.281 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_0 | mse | 0.937 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_0 | TimeSeries comparison | aml://artifactId/ExperimentRun/dcid.HD_9cbf07dc-db35-4700-adc3-92253a378992_0/TimeSeries comparison_1585555145.png |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_1 | AUC | 0.357 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_1 | pAUC | 0.562 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_1 | RMSE | 0.616 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_1 | mse | 0.333 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_1 | TimeSeries comparison | aml://artifactId/ExperimentRun/dcid.HD_9cbf07dc-db35-4700-adc3-92253a378992_1/TimeSeries comparison_1585555146.png |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_2 | AUC | 0.12 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_2 | pAUC | 0.581 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_2 | RMSE | 0.0969 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_2 | mse | 0.49 |
| HD_9cbf07dc-db35-4700-adc3-92253a378992_2 | TimeSeries comparison | aml://artifactId/ExperimentRun/dcid.HD_9cbf07dc-db35-4700-adc3-92253a378992_2/TimeSeries comparison_1585555076.png |

**Comment by awmatheson** [comment]
And example of a single run:

| Run ID | Parameter | Value |
| ----- | ----- | ----- |
| GitHubActionExperiment_1585252332_b5f3cd66 | Kernel type | linear |
| GitHubActionExperiment_1585252332_b5f3cd66 | Penalty | 1.0 |
| GitHubActionExperiment_1585252332_b5f3cd66 | Accuracy | 0.933 |
| GitHubActionExperiment_1585252332_b5f3cd66 | precision | 0.933 |
| GitHubActionExperiment_1585252332_b5f3cd66 | recall | 0.933 |
| GitHubActionExperiment_1585252332_b5f3cd66 | f1-score | 0.933 |
| GitHubActionExperiment_1585252332_b5f3cd66 | confusion_matrix | aml://artifactId/ExperimentRun/dcid.GitHubActionExperiment_1585252332_b5f3cd66/confusion_matrix |
| GitHubActionExperiment_1585252332_b5f3cd66 | confusion_matrix_unnormalized | aml://artifactId/ExperimentRun/dcid.GitHubActionExperiment_1585252332_b5f3cd66/confusion_matrix_unnormalized_1585253019.png |
| GitHubActionExperiment_1585252332_b5f3cd66 | confusion_matrix_normalized | aml://artifactId/ExperimentRun/dcid.GitHubActionExperiment_1585252332_b5f3cd66/confusion_matrix_normalized_1585253019.png |
| GitHubActionExperiment_1585252332_b5f3cd66 | Model Name | model.pkl |
